// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID                 int32
	Adult              pgtype.Bool
	BackdropPath       pgtype.Text
	GenreIds           []int32
	MovieID            int32
	MovieLanguage      pgtype.Text
	MovieOriginalTitle pgtype.Text
	MovieOverview      pgtype.Text
	Popularity         pgtype.Float8
	PosterPath         pgtype.Text
	ReleaseDate        pgtype.Text
	MovieTitle         string
	Video              pgtype.Bool
	VoteAverage        pgtype.Float8
	VoteCount          pgtype.Int8
}
