// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMovie(ctx context.Context, arg AddMovieParams) error
	GetMovieByDesc(ctx context.Context, dollar_1 pgtype.Text) ([]Movie, error)
	GetMovieByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]Movie, error)
	GetMovieByTitleAndDesc(ctx context.Context, arg GetMovieByTitleAndDescParams) ([]Movie, error)
}

var _ Querier = (*Queries)(nil)
